### ISSUE TITLE
sends this error when added a comment to Issue

### ISSUE THREAD

**Issue by daneshvar** [Commit451/skyhook#167] opened 2020-12-15 13:26 UTC
An error has occured on skyhook for your webhook with provider jira. Maybe you can copy/paste or screenshot this error if there is no sensitive information and open an issue on the skyhook GitHub.

Error: "TypeError: Cannot read property 'fields' of undefined\n at Jira.<anonymous> (/app/dist/provider/Jira.js:46:23)\n at Generator.next (<anonymous>)\n at /app/dist/provider/Jira.js:7:71\n at new Promise (<anonymous>)\n at __awaiter (/app/dist/provider/Jira.js:3:12)\n at Jira.parseData (/app/dist/provider/Jira.js:29:16)\n at Jira.<anonymous> (/app/dist/provider/BaseProvider.js:71:33)\n at Generator.next (<anonymous>)\n at /app/dist/provider/BaseProvider.js:7:71\n at new Promise (<anonymous>)"

**Comment by dscalzi** [comment] 2021-11-22 06:47
Duplicate of https://github.com/Commit451/skyhook/issues/152

**Closed by dscalzi** 2021-11-22 06:47 UTC
