### ISSUE TITLE
Error Integrate with jira when comment

### ISSUE THREAD

**Issue by samurailee** [Commit451/skyhook#171] opened 2021-02-25 07:31 UTC
Error: "TypeError: Cannot read property 'fields' of undefined\n at Jira.<anonymous> (/app/dist/provider/Jira.js:46:23)\n at Generator.next (<anonymous>)\n at /app/dist/provider/Jira.js:7:71\n at new Promise (<anonymous>)\n at __awaiter (/app/dist/provider/Jira.js:3:12)\n at Jira.parseData (/app/dist/provider/Jira.js:29:16)\n at Jira.<anonymous> (/app/dist/provider/BaseProvider.js:71:33)\n at Generator.next (<anonymous>)\n at /app/dist/provider/BaseProvider.js:7:71\n at new Promise (<anonymous>)"

**Comment by md-5** [comment] 2021-05-06 22:48
Can confirm

**Comment by foodgy** [comment] 2021-05-09 17:00
Confirm

**Comment by anebi** [comment] 2021-05-25 10:26
Hi, Same here using latest docker image

`Error: "TypeError: Cannot read property 'fields' of undefined\n at Jira.<anonymous> (/usr/src/app/dist/provider/Jira.js:46:23)\n at Generator.next (<anonymous>)\n at /usr/src/app/dist/provider/Jira.js:7:71\n at new Promise (<anonymous>)\n at __awaiter (/usr/src/app/dist/provider/Jira.js:3:12)\n at Jira.parseData (/usr/src/app/dist/provider/Jira.js:29:16)\n at Jira.<anonymous> (/usr/src/app/dist/provider/BaseProvider.js:72:33)\n at Generator.next (<anonymous>)\n at /usr/src/app/dist/provider/BaseProvider.js:7:71\n at new Promise (<anonymous>)"`

**Comment by dscalzi** [comment] 2021-11-22 06:39
Duplicate of https://github.com/Commit451/skyhook/issues/171

**Closed by dscalzi** 2021-11-22 06:39 UTC
