### ISSUE TITLE
Codacy error

### ISSUE THREAD

**Issue by duncte123** [Commit451/skyhook#105] opened 2018-09-10 10:54 UTC
When a commit was finished on Codacy this error was displayed within discord:

```
An error has occured on skyhook for your webhook with provider codacy. Maybe you can copy/paste or screenshot this error if there is no sensitive information and open an issue on the skyhook GitHub.

Error: "TypeError: Cannot read property 'fixed_count' of undefined
 at Codacy.<anonymous> (/app/dist/provider/Codacy.js:29:62)
 at Generator.next (<anonymous>)
 at /app/dist/provider/Codacy.js:6:71
 at new Promise (<anonymous>)
 at __awaiter (/app/dist/provider/Codacy.js:2:12)
 at Codacy.parseData (/app/dist/provider/Codacy.js:21:16)
 at Codacy.<anonymous> (/app/dist/provider/BaseProvider.js:57:33)
 at Generator.next (<anonymous>)
 at /app/dist/provider/BaseProvider.js:6:71
 at new Promise (<anonymous>)"
```

**Comment by dscalzi** [comment] 2018-09-14 03:05
Would it be possible for you to send the webhook body? As far as I know no changes have been made to the webhook format. If that's not possible, could you tell me if your commit had 0 fixed issues and 0 new issues? It may be possible that the results property is not sent when there are no issues in either category. I see nothing that would imply this on codacy's documentation though.

Best help would be to have the full webhook body, though.

**Comment by duncte123** [comment] 2018-09-14 06:43
I can't find what codacy was sending but what I can tell you is that the fixed count was 10 and that there where 5 new issues

**Comment by dscalzi** [comment] 2018-09-14 07:06
Not sure what the issue is then, codacy's documentation hasnt changed.

**Comment by duncte123** [comment] 2018-09-14 07:29
I'll try to debug log the data that codacy is sending

**Comment by duncte123** [comment] 2018-09-14 08:02
You might want to add a null check to the issues because it seems that codacy isn't sending them with pull requests

```json
{
  "commit": {
    "data": {
      "uuid": "2552800921661be79d4f039b739d022f8e86fd10",
      "urls": {
        "delta": "https:\/\/app.codacy.com\/app\/DuncteBot\/SkyBot\/commit?cid=247838629"
      }
    }
  }
}
```

**Comment by dscalzi** [comment] 2018-09-22 09:59
Should be fixed next time the site is synced.

**Closed by dscalzi** 2018-09-22 09:59 UTC
Labels: bug
