### ISSUE TITLE
Issue when someone push changes to Bitbucket.

### ISSUE THREAD

**Issue by szczepix** [Commit451/skyhook#92] opened 2018-08-07 09:32 UTC
`An error has occured on skyhook for your webhook with provider bitbucket. Maybe you can screenshot this error and open an issue on the skyhook GitHub. Error: "TypeError: Cannot read property 'length' of undefined\n    at BitBucket.<anonymous> (/app/dist/providers/Bitbucket.js:60:46)\n    at Generator.next (<anonymous>)\n    at /app/dist/providers/Bitbucket.js:6:71\n    at new Promise (<anonymous>)\n    at __awaiter (/app/dist/providers/Bitbucket.js:2:12)\n    at BitBucket.repoPush (/app/dist/providers/Bitbucket.js:48:16)\n    at BitBucket.<anonymous> (/app/dist/model/BaseProvider.js:56:33)\n    at Generator.next (<anonymous>)\n    at fulfilled (/app/dist/model/BaseProvider.js:3:58)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"`

`An error has occured on skyhook for your webhook with provider bitbucket. Maybe you can screenshot this error and open an issue on the skyhook GitHub. Error: "TypeError: Cannot read property 'length' of undefined\n    at BitBucket.<anonymous> (/app/dist/providers/Bitbucket.js:60:46)\n    at Generator.next (<anonymous>)\n    at /app/dist/providers/Bitbucket.js:6:71\n    at new Promise (<anonymous>)\n    at __awaiter (/app/dist/providers/Bitbucket.js:2:12)\n    at BitBucket.repoPush (/app/dist/providers/Bitbucket.js:48:16)\n    at BitBucket.<anonymous> (/app/dist/model/BaseProvider.js:56:33)\n    at Generator.next (<anonymous>)\n    at fulfilled (/app/dist/model/BaseProvider.js:3:58)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
NEW MESSAGES`

`BitBucketBOTToday at 11:23 AM
An error has occured on skyhook for your webhook with provider bitbucket. Maybe you can screenshot this error and open an issue on the skyhook GitHub. Error: "TypeError: Cannot read property 'length' of undefined\n    at BitBucket.<anonymous> (/app/dist/providers/Bitbucket.js:60:46)\n    at Generator.next (<anonymous>)\n    at /app/dist/providers/Bitbucket.js:6:71\n    at new Promise (<anonymous>)\n    at __awaiter (/app/dist/providers/Bitbucket.js:2:12)\n    at BitBucket.repoPush (/app/dist/providers/Bitbucket.js:48:16)\n    at BitBucket.<anonymous> (/app/dist/model/BaseProvider.js:56:33)\n    at Generator.next (<anonymous>)\n    at fulfilled (/app/dist/model/BaseProvider.js:3:58)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"`

![screen](https://user-images.githubusercontent.com/1363477/43767449-7cef8bb2-9a35-11e8-88b9-04c9d1ab7e1c.png)

**Comment by dscalzi** [comment] 2018-08-07 09:55
The only thing I can think of is that bitbucket removed the `changes` property. Would it be possible for you to post the content of the webhook? You could setup a mock webhook with https://ngrok.com/ and then trigger the push event.

**Comment by szczepix** [comment] 2018-08-07 10:03
I'am using this: https://skyhook.glitch.me/ it's yours?

**Comment by szczepix** [comment] 2018-08-07 10:08
![screen_2](https://user-images.githubusercontent.com/1363477/43769649-85de9d1c-9a3a-11e8-9a64-2741ced09e13.png)

**Comment by dscalzi** [comment] 2018-08-07 10:11
Yes, but I was asking for the webhook payload. If you are not sure how to do it I'll have to look into this later. Don't have time to set it up at the moment.

**Comment by dscalzi** [comment] 2018-08-07 20:32
Cannot reproduce. Can you tell me exactly what you did on bitbucket to trigger this?

**Comment by szczepix** [comment] 2018-08-08 09:44
![image](https://user-images.githubusercontent.com/1363477/43829877-5811609c-9b00-11e8-8607-6112ae40fe72.png)

**Comment by szczepix** [comment] 2018-08-08 09:47
btw. look like it works fine now

**Comment by szczepix** [comment] 2018-08-08 11:05
It's back 
![image](https://user-images.githubusercontent.com/1363477/43833626-b0f844fe-9b0b-11e8-92a2-0de9f9306d58.png)

**Comment by szczepix** [comment] 2018-08-08 13:41
At the moment it does not work and only sends embedded with **Skyhook Error**

**Comment by szczepix** [comment] 2018-08-09 12:09
It's exist on push to branch, merge branch and create pull request. It's exist randomly.

**Comment by dscalzi** [comment] 2018-08-10 08:10
Is any data missing? I noticed you have an embed delivered in your screenshot. If no data is lost I can just suppress this error.

**Comment by szczepix** [comment] 2018-08-10 14:28
Please do it sth with this. Maybe you can just log this things instead of sending embedded message to discord.
![image](https://user-images.githubusercontent.com/1363477/43963337-517beb10-9cba-11e8-9eb6-a38263063f68.png)
![image](https://user-images.githubusercontent.com/1363477/43963286-2905c4e4-9cba-11e8-91f7-bc98c4840603.png)

**Comment by dscalzi** [comment] 2018-08-10 22:51
I don't think this is a problem with skyhook. I've tested the Bitbucket provider several times and the push event worked fine. Please ensure that you've properly setup the webhook.

In order to do anything else I need you to setup [ngrok](https://ngrok.com/) and setup another webhook on bitbucket which points to ngrok. It will allow you to intercept the payload which is being sent. Once you get the payload please report it back here. I am closing this until then.

**Closed by dscalzi** 2018-08-10 22:51 UTC
Labels: reply needed
