### ISSUE TITLE
502 or timeout error on Bitbucket webhook

### ISSUE THREAD

**Issue by TehnoMag** [Commit451/skyhook#136] opened 2019-11-23 13:30 UTC
Request status: TIMEOUT
Elapsed time: 61063ms
Request time: a minute ago (Saturday, November 23rd 2019, 4:26:38 pm)

Header|Value
-- | --
X-Request-UUID | 8fe14157-2ff3-4750-a3a9-ca3e2ab4efba
X-Event-Key | repo:push
X-Event-Time | Sat, 23 Nov 2019 13:25:35 GMT
X-Attempt-Number | 1
X-Hook-UUID | 14e44108-dc72-4885-9609-b54fa5473ae5
User-Agent | Bitbucket-Webhooks/2.0
Content-Type | application/json

HTTP status: 502
Elapsed time: 45529ms
Request time: 10 minutes ago (Saturday, November 23rd 2019, 4:21:49 pm)

Header|Value
-- | --
Date | Sat, 23 Nov 2019 13:21:49 GMT
Content-Length | 138
Content-Type | text/html
Connection | keep-alive
Server | awselb/2.0

**Comment by higgs01** [comment] 2019-11-24 18:06
seems to be related/duplicate of to https://github.com/Commit451/skyhook/issues/135

**Closed** 2019-11-28 03:05 UTC
